name: release

on:
  push:
    branches: [ "main" ]
    paths:
      - assets/version.txt
      
jobs:
  build-osx:
    permissions: write-all
    runs-on: 	macos-latest
    defaults:
      run:
        working-directory: ./build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: bash ./build-osx.sh
    - name: Archive OSX Package
      uses: actions/upload-artifact@v4
      with:
        name: osx-pkg
        path: src/StarEachOther.Desktop/bin/GithubStarEachOther_osx_x64.tar.gz
        retention-days: 1
  build-android:
    permissions: write-all
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Build
      env:
        ANDROID_FILENAME: ${{ secrets.ANDROID_FILENAME }}
        ANDROID_KEYNAME: ${{ secrets.ANDROID_KEYNAME }}
        ANDROID_KEYPASSWORD: ${{ secrets.ANDROID_KEYPASSWORD }}
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }} 
      run: bash ./build-android.sh
    - name: Archive Android Package
      uses: actions/upload-artifact@v4
      with:
        name: android-pkg
        path: src/StarEachOther.Android/bin/GithubStarEachOther_android.apk
        retention-days: 1
  build-win:
    permissions: write-all
    runs-on: windows-latest 
    defaults:
      run:
        working-directory: ./build
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: ./build-win.cmd
    - name: Archive Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: win-pkg
        path: src/StarEachOther.Desktop/bin/GithubStarEachOther_win_x64.exe
        retention-days: 1
  build-linux:
      permissions: write-all
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./build
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: bash ./build-linux.sh
      - name: Archive Linux Package
        uses: actions/upload-artifact@v4
        with:
          name: linux-pkg
          path: src/StarEachOther.Desktop/bin/GithubStarEachOther_linux_x64.tar.gz
          retention-days: 1
  release:
    permissions: write-all
    runs-on: ubuntu-latest 
    needs: [build-android,build-win,build-linux,build-osx]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SetVersion
      id: SetVersion
      run: |
        echo "version=$(cat ./assets/version.txt)" >> $GITHUB_OUTPUT
    - name: Download android-pkg
      uses: actions/download-artifact@v4
      with:
          name: android-pkg
          path: output
    - name: Download win-pkg
      uses: actions/download-artifact@v4
      with:
          name: win-pkg
          path: output
    - name: Download linux-pkg
      uses: actions/download-artifact@v4
      with:
          name: linux-pkg
          path: output
    - name: Download osx-pkg
      uses: actions/download-artifact@v4
      with:
          name: osx-pkg
          path: output
    - name: release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.SetVersion.outputs.version }}
        artifacts: "output/*"
        bodyFile: "assets/version-change.md"